# Service request

---

# Service response

float64 grid_size # Distance between grid units (metres)
float64 lat_size  # Quantity between lat lines  (deg)
float64 long_size # Quantity between long lines (deg)
