# Service request

---

# Service response

float32 grid_size # Distance between grid units (metres)
float32 lat_size  # Quantity between lat lines  (deg)
float32 long_size # Quantity between long lines (deg)
